name: alpine

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    container: alpine:latest
    strategy:
      fail-fast: false
      matrix:
        cc: [ gcc, clang ]
    steps:
    - name: dependencies
      run: |
        apk -q update
        apk add git build-base clang clang-analyzer \
          linux-pam-dev openssl-dev libfido2-dev \
          autoconf automake libtool pkgconfig
    - name: fix permissions on workdir
      run: chown root:wheel "${GITHUB_WORKSPACE}"
    - name: checkout pam-u2f
      uses: actions/checkout@v2
    - name: build
      env:
        CC: ${{ matrix.cc }}
        USER: root
      run: |
        /bin/bash -eux build-aux/ci/build-linux-${CC%-*}.sh
